# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: hab_development
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] %>
  database: hab_test
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  host: <%= Rails.application.credentials.production[:database][:host] %>
  database: <%= Rails.application.credentials.production[:database][:database] %>
  username: <%= Rails.application.credentials.production[:database][:username] %>
  password: <%= Rails.application.credentials.production[:database][:password] %>
